### ISSUE TITLE
Riot 3.0?

### ISSUE THREAD

**Issue by alvin** [Joylei/riot-format#1]
![image](https://cloud.githubusercontent.com/assets/16319/20619604/49d077b0-b2aa-11e6-92ef-072c08e9ec9d.png)

Spent some time trying to sort out why the format function fails with the above console log with Riot 3.0.  So far, no luck.  My tag looks as follows:

<h5>{ data.classes[state.id].nextScheduledDate ? format(data.classes[state.id].nextScheduledDate, 'date', 'mmm d, yyyy') : 'TBD'}</h5>

If anyone could offer any advice, I'd be all ears!

**Comment by Joylei** [comment]
@alvin sorry for delay. will have a look.

**Comment by Joylei** [comment]
@alvin not sure what is wrong with your tag. I upgraded the riot version to 3.0.1 and it seems fine with the examples. can you post your code to http://jsfiddle.net, so I can figure out what's going on.

**Comment by Joylei** [comment]
@alvin does you import the module 'riot-format' and apply it to 'riot' module?
```
var riot = require('riot');
var format = require('riot-format');
format(riot);
```

only after you do that, the format function can take effect.

**Comment by Joylei** [comment]
@alvin 

It seems that riot@3.0+ has changed its internal logical, so riot-format does not work.

**Comment by alvin** [comment]
Thanks for looking.  With your latest changes to master it works as a global for me (I  had tried this before but it didn't work).  I don't mind using it that way for now.
